version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules # Do not map this folder to local.
      - .:/app # Map present working dir to /app in container.
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
        - /app/node_modules
        - .:/app
    command: ["npm","run","test"] # Override container startup command.